### ISSUE TITLE
6.3 install does not work - Error: '/opt/haiwen/conf/gunicorn.conf' doesn't exist

### ISSUE THREAD

**Issue by crscheid** [cmer/docker-seafile#6]
I believe with the 6.3 community edition update, the install process doesn't work any more. The following error was received.

```
seafile_1  | Generating download URL for:
seafile_1  |   VERSION: latest
seafile_1  |   ARCHITECTURE: x86-64
seafile_1  |   EDITION: Community
seafile_1  | 
seafile_1  | Installing Community Edition...
seafile_1  | 
seafile_1  | Downloading & Extracting https://download.seadrive.org/seafile-server_6.3.0_x86-64.tar.gz...
seafile_1  | 
seafile_1  | Done!
seafile_1  | Using Community Edition...
seafile_1  | Installation path: /opt/haiwen/seafile-server-6.3.0
seafile_1  | 
seafile_1  | Seahub is not running
seafile_1  | Done.
seafile_1  | 
seafile_1  | 
seafile_1  | seafile server not running yet
seafile_1  | Done.
seafile_1  | 
seafile_1  | [06/01/18 19:07:55] ../common/session.c(132): using config file /opt/haiwen/conf/ccnet.conf
seafile_1  | Starting seafile server, please wait ...
seafile_1  | Seafile server started
seafile_1  | 
seafile_1  | Done.
seafile_1  | 
seafile_1  | Starting seahub at port 8000 ...
seafile_1  | 
seafile_1  | Error: '/opt/haiwen/conf/gunicorn.conf' doesn't exist
seafile_1  | Error:Seahub failed to start.
seafile_1  | Please try to run "./seahub.sh start" again
seafile_seafile_1 exited with code 1
```

Using the following docker-compose.yml configuration:

```
version: '2.2'
services:

  # The application itself
  seafile:
    restart: unless-stopped
    image: cmer/seafile:latest
    volumes:
      - /Users/xxxxx/Desktop/seafile/data:/seafile
    environment:
      SEAFILE_NAME: TSeafile
      SEAFILE_ADDRESS: 10.0.1.3
      SEAFILE_ADMIN: xxxx.xxxx@gmail.com
      SEAFILE_ADMIN_PW: xxxxxxxxx
    # Already exposes ports 8000 8082
    ports:
      - "8000:8000"
      - "8082:8082"
```
